global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # cAdvisor Container Metrics (for system monitoring) - This is the main one we need
  - job_name: 'cadvisor-containers'
    static_configs:
      - targets: ['cadvisor:8080']  # Use internal Docker service name
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    
    # Add labels for better organization
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'cadvisor'
      - source_labels: [__address__]
        target_label: metrics_type
        replacement: 'system'
    
    # Filter to only container metrics AND only agent containers with monitoring labels
    metric_relabel_configs:
      # Keep only container metrics
      - source_labels: [__name__]
        regex: 'container_(.*)'
        action: keep
      # Keep only metrics for containers with monitoring=true label
      - source_labels: [container_label_monitoring]
        regex: 'true'
        action: keep
      # Add useful labels from container labels for better querying
      - source_labels: [container_label_agent_type]
        target_label: agent_type
        action: replace
      - source_labels: [container_label_deployment_id]
        target_label: deployment_id
        action: replace
      - source_labels: [container_label_agent_id]
        target_label: agent_id
        action: replace
      - source_labels: [container_label_hiring_id]
        target_label: hiring_id
        action: replace
      - source_labels: [container_label_user_id]
        target_label: user_id
        action: replace

  # AgentHub Business Metrics (for billing and business context)
  - job_name: 'agenthub-business'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Use host.docker.internal to access host from container
    metrics_path: '/api/v1/metrics/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s
    
    # Add labels for better organization
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'agenthub-business'
      - source_labels: [__address__]
        target_label: metrics_type
        replacement: 'business'

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']  # Use host.docker.internal for host network mode
    scrape_interval: 30s
    scrape_timeout: 10s
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'node-exporter'

# Alerting rules (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

# Recording rules (optional)
# rule_files:
#   - "recording_rules.yml"
