# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

from typing import Protocol, runtime_checkable
from uuid import UUID
from decimal import Decimal

from beeai_server.domain.models.agent import Credits


@runtime_checkable
class ICreditsRepository(Protocol):
    async def create(self, credits: Credits) -> None: ...
    async def get(self, *, user_id: UUID) -> Credits: ...
    async def update(self, *, credits: Credits) -> None: ...
    async def add_credits(self, *, user_id: UUID, amount: Decimal) -> bool: ...
    async def deduct_credits(self, *, user_id: UUID, amount: Decimal) -> bool: ...
    async def get_balance(self, *, user_id: UUID) -> Decimal: ... 