# Copyright 2025 © BeeAI a Series of LF Projects, LLC
# SPDX-License-Identifier: Apache-2.0

from typing import Protocol, runtime_checkable, AsyncIterator
from uuid import UUID

from beeai_server.domain.models.agent import Task


@runtime_checkable
class ITaskRepository(Protocol):
    async def create(self, task: Task) -> None: ...
    async def get(self, *, task_id: UUID) -> Task: ...
    async def list_by_agent(self, *, agent_id: UUID) -> AsyncIterator[Task]: ...
    async def list_by_client(self, *, client_id: UUID) -> AsyncIterator[Task]: ...
    async def update(self, *, task: Task) -> None: ...
    async def delete(self, *, task_id: UUID) -> None: ...
    async def get_active_tasks_by_agent(self, *, agent_id: UUID) -> AsyncIterator[Task]: ... 